# Generated by Django 2.1 on 2018-08-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=32, null=True)),
                ('rated', models.CharField(blank=True, max_length=32, null=True)),
                ('released', models.CharField(blank=True, max_length=32, null=True)),
                ('runtime', models.CharField(blank=True, max_length=32, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=32, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=32, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('total_seasons', models.CharField(blank=True, max_length=32, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, max_length=32, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=32)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
